// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FileHashesColumns holds the columns for the "file_hashes" table.
	FileHashesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString, Unique: true},
		{Name: "minio_object", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "mime_type", Type: field.TypeString, Nullable: true},
		{Name: "reference_count", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FileHashesTable holds the schema information for the "file_hashes" table.
	FileHashesTable = &schema.Table{
		Name:       "file_hashes",
		Columns:    FileHashesColumns,
		PrimaryKey: []*schema.Column{FileHashesColumns[0]},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeInt, Default: 0},
		{Name: "size", Type: field.TypeInt64, Default: 0},
		{Name: "mime_type", Type: field.TypeString, Nullable: true},
		{Name: "file_hash", Type: field.TypeString, Nullable: true},
		{Name: "minio_object", Type: field.TypeString, Nullable: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "node_parent", Type: field.TypeInt, Nullable: true},
		{Name: "user_nodes", Type: field.TypeInt},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "nodes_nodes_parent",
				Columns:    []*schema.Column{NodesColumns[11]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "nodes_users_nodes",
				Columns:    []*schema.Column{NodesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SharesColumns holds the columns for the "shares" table.
	SharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "share_type", Type: field.TypeInt, Default: 0},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "access_count", Type: field.TypeInt, Default: 0},
		{Name: "max_access_count", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "node_shares", Type: field.TypeInt},
		{Name: "user_shares", Type: field.TypeInt},
	}
	// SharesTable holds the schema information for the "shares" table.
	SharesTable = &schema.Table{
		Name:       "shares",
		Columns:    SharesColumns,
		PrimaryKey: []*schema.Column{SharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "shares_nodes_shares",
				Columns:    []*schema.Column{SharesColumns[9]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "shares_users_shares",
				Columns:    []*schema.Column{SharesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "total_quota", Type: field.TypeInt64, Default: 10737418240},
		{Name: "total_used", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FileHashesTable,
		NodesTable,
		SharesTable,
		UsersTable,
	}
)

func init() {
	NodesTable.ForeignKeys[0].RefTable = NodesTable
	NodesTable.ForeignKeys[1].RefTable = UsersTable
	SharesTable.ForeignKeys[0].RefTable = NodesTable
	SharesTable.ForeignKeys[1].RefTable = UsersTable
}
