// Code generated by ent, DO NOT EDIT.

package share

import (
	"gopan-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCode, v))
}

// ShareType applies equality check predicate on the "share_type" field. It's identical to ShareTypeEQ.
func ShareType(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldShareType, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPassword, v))
}

// AccessCount applies equality check predicate on the "access_count" field. It's identical to AccessCountEQ.
func AccessCount(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldAccessCount, v))
}

// MaxAccessCount applies equality check predicate on the "max_access_count" field. It's identical to MaxAccessCountEQ.
func MaxAccessCount(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldMaxAccessCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldCode, v))
}

// ShareTypeEQ applies the EQ predicate on the "share_type" field.
func ShareTypeEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldShareType, v))
}

// ShareTypeNEQ applies the NEQ predicate on the "share_type" field.
func ShareTypeNEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldShareType, v))
}

// ShareTypeIn applies the In predicate on the "share_type" field.
func ShareTypeIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldShareType, vs...))
}

// ShareTypeNotIn applies the NotIn predicate on the "share_type" field.
func ShareTypeNotIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldShareType, vs...))
}

// ShareTypeGT applies the GT predicate on the "share_type" field.
func ShareTypeGT(v int) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldShareType, v))
}

// ShareTypeGTE applies the GTE predicate on the "share_type" field.
func ShareTypeGTE(v int) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldShareType, v))
}

// ShareTypeLT applies the LT predicate on the "share_type" field.
func ShareTypeLT(v int) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldShareType, v))
}

// ShareTypeLTE applies the LTE predicate on the "share_type" field.
func ShareTypeLTE(v int) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldShareType, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldExpiresAt))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldPassword, v))
}

// AccessCountEQ applies the EQ predicate on the "access_count" field.
func AccessCountEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldAccessCount, v))
}

// AccessCountNEQ applies the NEQ predicate on the "access_count" field.
func AccessCountNEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldAccessCount, v))
}

// AccessCountIn applies the In predicate on the "access_count" field.
func AccessCountIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldAccessCount, vs...))
}

// AccessCountNotIn applies the NotIn predicate on the "access_count" field.
func AccessCountNotIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldAccessCount, vs...))
}

// AccessCountGT applies the GT predicate on the "access_count" field.
func AccessCountGT(v int) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldAccessCount, v))
}

// AccessCountGTE applies the GTE predicate on the "access_count" field.
func AccessCountGTE(v int) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldAccessCount, v))
}

// AccessCountLT applies the LT predicate on the "access_count" field.
func AccessCountLT(v int) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldAccessCount, v))
}

// AccessCountLTE applies the LTE predicate on the "access_count" field.
func AccessCountLTE(v int) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldAccessCount, v))
}

// MaxAccessCountEQ applies the EQ predicate on the "max_access_count" field.
func MaxAccessCountEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldMaxAccessCount, v))
}

// MaxAccessCountNEQ applies the NEQ predicate on the "max_access_count" field.
func MaxAccessCountNEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldMaxAccessCount, v))
}

// MaxAccessCountIn applies the In predicate on the "max_access_count" field.
func MaxAccessCountIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldMaxAccessCount, vs...))
}

// MaxAccessCountNotIn applies the NotIn predicate on the "max_access_count" field.
func MaxAccessCountNotIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldMaxAccessCount, vs...))
}

// MaxAccessCountGT applies the GT predicate on the "max_access_count" field.
func MaxAccessCountGT(v int) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldMaxAccessCount, v))
}

// MaxAccessCountGTE applies the GTE predicate on the "max_access_count" field.
func MaxAccessCountGTE(v int) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldMaxAccessCount, v))
}

// MaxAccessCountLT applies the LT predicate on the "max_access_count" field.
func MaxAccessCountLT(v int) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldMaxAccessCount, v))
}

// MaxAccessCountLTE applies the LTE predicate on the "max_access_count" field.
func MaxAccessCountLTE(v int) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldMaxAccessCount, v))
}

// MaxAccessCountIsNil applies the IsNil predicate on the "max_access_count" field.
func MaxAccessCountIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldMaxAccessCount))
}

// MaxAccessCountNotNil applies the NotNil predicate on the "max_access_count" field.
func MaxAccessCountNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldMaxAccessCount))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.Node) predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Share) predicate.Share {
	return predicate.Share(sql.NotPredicates(p))
}
