// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FileHash is the predicate function for filehash builders.
type FileHash func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// Share is the predicate function for share builders.
type Share func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
