// Code generated by ent, DO NOT EDIT.

package filehash

import (
	"gopan-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldID, id))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldHash, v))
}

// MinioObject applies equality check predicate on the "minio_object" field. It's identical to MinioObjectEQ.
func MinioObject(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldMinioObject, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldSize, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldMimeType, v))
}

// ReferenceCount applies equality check predicate on the "reference_count" field. It's identical to ReferenceCountEQ.
func ReferenceCount(v int) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldReferenceCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldUpdatedAt, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldContainsFold(FieldHash, v))
}

// MinioObjectEQ applies the EQ predicate on the "minio_object" field.
func MinioObjectEQ(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldMinioObject, v))
}

// MinioObjectNEQ applies the NEQ predicate on the "minio_object" field.
func MinioObjectNEQ(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldMinioObject, v))
}

// MinioObjectIn applies the In predicate on the "minio_object" field.
func MinioObjectIn(vs ...string) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldMinioObject, vs...))
}

// MinioObjectNotIn applies the NotIn predicate on the "minio_object" field.
func MinioObjectNotIn(vs ...string) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldMinioObject, vs...))
}

// MinioObjectGT applies the GT predicate on the "minio_object" field.
func MinioObjectGT(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldMinioObject, v))
}

// MinioObjectGTE applies the GTE predicate on the "minio_object" field.
func MinioObjectGTE(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldMinioObject, v))
}

// MinioObjectLT applies the LT predicate on the "minio_object" field.
func MinioObjectLT(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldMinioObject, v))
}

// MinioObjectLTE applies the LTE predicate on the "minio_object" field.
func MinioObjectLTE(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldMinioObject, v))
}

// MinioObjectContains applies the Contains predicate on the "minio_object" field.
func MinioObjectContains(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldContains(FieldMinioObject, v))
}

// MinioObjectHasPrefix applies the HasPrefix predicate on the "minio_object" field.
func MinioObjectHasPrefix(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldHasPrefix(FieldMinioObject, v))
}

// MinioObjectHasSuffix applies the HasSuffix predicate on the "minio_object" field.
func MinioObjectHasSuffix(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldHasSuffix(FieldMinioObject, v))
}

// MinioObjectEqualFold applies the EqualFold predicate on the "minio_object" field.
func MinioObjectEqualFold(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEqualFold(FieldMinioObject, v))
}

// MinioObjectContainsFold applies the ContainsFold predicate on the "minio_object" field.
func MinioObjectContainsFold(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldContainsFold(FieldMinioObject, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldSize, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeIsNil applies the IsNil predicate on the "mime_type" field.
func MimeTypeIsNil() predicate.FileHash {
	return predicate.FileHash(sql.FieldIsNull(FieldMimeType))
}

// MimeTypeNotNil applies the NotNil predicate on the "mime_type" field.
func MimeTypeNotNil() predicate.FileHash {
	return predicate.FileHash(sql.FieldNotNull(FieldMimeType))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.FileHash {
	return predicate.FileHash(sql.FieldContainsFold(FieldMimeType, v))
}

// ReferenceCountEQ applies the EQ predicate on the "reference_count" field.
func ReferenceCountEQ(v int) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldReferenceCount, v))
}

// ReferenceCountNEQ applies the NEQ predicate on the "reference_count" field.
func ReferenceCountNEQ(v int) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldReferenceCount, v))
}

// ReferenceCountIn applies the In predicate on the "reference_count" field.
func ReferenceCountIn(vs ...int) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldReferenceCount, vs...))
}

// ReferenceCountNotIn applies the NotIn predicate on the "reference_count" field.
func ReferenceCountNotIn(vs ...int) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldReferenceCount, vs...))
}

// ReferenceCountGT applies the GT predicate on the "reference_count" field.
func ReferenceCountGT(v int) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldReferenceCount, v))
}

// ReferenceCountGTE applies the GTE predicate on the "reference_count" field.
func ReferenceCountGTE(v int) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldReferenceCount, v))
}

// ReferenceCountLT applies the LT predicate on the "reference_count" field.
func ReferenceCountLT(v int) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldReferenceCount, v))
}

// ReferenceCountLTE applies the LTE predicate on the "reference_count" field.
func ReferenceCountLTE(v int) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldReferenceCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FileHash {
	return predicate.FileHash(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FileHash) predicate.FileHash {
	return predicate.FileHash(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FileHash) predicate.FileHash {
	return predicate.FileHash(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FileHash) predicate.FileHash {
	return predicate.FileHash(sql.NotPredicates(p))
}
