// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gopan-server/ent/filehash"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FileHash is the model entity for the FileHash schema.
type FileHash struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// File hash (MD5 or SHA256)
	Hash string `json:"hash,omitempty"`
	// MinIO object name/path
	MinioObject string `json:"minio_object,omitempty"`
	// File size in bytes
	Size int64 `json:"size,omitempty"`
	// MIME type
	MimeType string `json:"mime_type,omitempty"`
	// Number of files referencing this hash
	ReferenceCount int `json:"reference_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FileHash) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case filehash.FieldID, filehash.FieldSize, filehash.FieldReferenceCount:
			values[i] = new(sql.NullInt64)
		case filehash.FieldHash, filehash.FieldMinioObject, filehash.FieldMimeType:
			values[i] = new(sql.NullString)
		case filehash.FieldCreatedAt, filehash.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FileHash fields.
func (fh *FileHash) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case filehash.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fh.ID = int(value.Int64)
		case filehash.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				fh.Hash = value.String
			}
		case filehash.FieldMinioObject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field minio_object", values[i])
			} else if value.Valid {
				fh.MinioObject = value.String
			}
		case filehash.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				fh.Size = value.Int64
			}
		case filehash.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				fh.MimeType = value.String
			}
		case filehash.FieldReferenceCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reference_count", values[i])
			} else if value.Valid {
				fh.ReferenceCount = int(value.Int64)
			}
		case filehash.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				fh.CreatedAt = value.Time
			}
		case filehash.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				fh.UpdatedAt = value.Time
			}
		default:
			fh.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FileHash.
// This includes values selected through modifiers, order, etc.
func (fh *FileHash) Value(name string) (ent.Value, error) {
	return fh.selectValues.Get(name)
}

// Update returns a builder for updating this FileHash.
// Note that you need to call FileHash.Unwrap() before calling this method if this FileHash
// was returned from a transaction, and the transaction was committed or rolled back.
func (fh *FileHash) Update() *FileHashUpdateOne {
	return NewFileHashClient(fh.config).UpdateOne(fh)
}

// Unwrap unwraps the FileHash entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fh *FileHash) Unwrap() *FileHash {
	_tx, ok := fh.config.driver.(*txDriver)
	if !ok {
		panic("ent: FileHash is not a transactional entity")
	}
	fh.config.driver = _tx.drv
	return fh
}

// String implements the fmt.Stringer.
func (fh *FileHash) String() string {
	var builder strings.Builder
	builder.WriteString("FileHash(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fh.ID))
	builder.WriteString("hash=")
	builder.WriteString(fh.Hash)
	builder.WriteString(", ")
	builder.WriteString("minio_object=")
	builder.WriteString(fh.MinioObject)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", fh.Size))
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(fh.MimeType)
	builder.WriteString(", ")
	builder.WriteString("reference_count=")
	builder.WriteString(fmt.Sprintf("%v", fh.ReferenceCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fh.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fh.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FileHashes is a parsable slice of FileHash.
type FileHashes []*FileHash
