// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gopan-server/ent/filehash"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileHashCreate is the builder for creating a FileHash entity.
type FileHashCreate struct {
	config
	mutation *FileHashMutation
	hooks    []Hook
}

// SetHash sets the "hash" field.
func (fhc *FileHashCreate) SetHash(s string) *FileHashCreate {
	fhc.mutation.SetHash(s)
	return fhc
}

// SetMinioObject sets the "minio_object" field.
func (fhc *FileHashCreate) SetMinioObject(s string) *FileHashCreate {
	fhc.mutation.SetMinioObject(s)
	return fhc
}

// SetSize sets the "size" field.
func (fhc *FileHashCreate) SetSize(i int64) *FileHashCreate {
	fhc.mutation.SetSize(i)
	return fhc
}

// SetMimeType sets the "mime_type" field.
func (fhc *FileHashCreate) SetMimeType(s string) *FileHashCreate {
	fhc.mutation.SetMimeType(s)
	return fhc
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (fhc *FileHashCreate) SetNillableMimeType(s *string) *FileHashCreate {
	if s != nil {
		fhc.SetMimeType(*s)
	}
	return fhc
}

// SetReferenceCount sets the "reference_count" field.
func (fhc *FileHashCreate) SetReferenceCount(i int) *FileHashCreate {
	fhc.mutation.SetReferenceCount(i)
	return fhc
}

// SetNillableReferenceCount sets the "reference_count" field if the given value is not nil.
func (fhc *FileHashCreate) SetNillableReferenceCount(i *int) *FileHashCreate {
	if i != nil {
		fhc.SetReferenceCount(*i)
	}
	return fhc
}

// SetCreatedAt sets the "created_at" field.
func (fhc *FileHashCreate) SetCreatedAt(t time.Time) *FileHashCreate {
	fhc.mutation.SetCreatedAt(t)
	return fhc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fhc *FileHashCreate) SetNillableCreatedAt(t *time.Time) *FileHashCreate {
	if t != nil {
		fhc.SetCreatedAt(*t)
	}
	return fhc
}

// SetUpdatedAt sets the "updated_at" field.
func (fhc *FileHashCreate) SetUpdatedAt(t time.Time) *FileHashCreate {
	fhc.mutation.SetUpdatedAt(t)
	return fhc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fhc *FileHashCreate) SetNillableUpdatedAt(t *time.Time) *FileHashCreate {
	if t != nil {
		fhc.SetUpdatedAt(*t)
	}
	return fhc
}

// Mutation returns the FileHashMutation object of the builder.
func (fhc *FileHashCreate) Mutation() *FileHashMutation {
	return fhc.mutation
}

// Save creates the FileHash in the database.
func (fhc *FileHashCreate) Save(ctx context.Context) (*FileHash, error) {
	fhc.defaults()
	return withHooks(ctx, fhc.sqlSave, fhc.mutation, fhc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fhc *FileHashCreate) SaveX(ctx context.Context) *FileHash {
	v, err := fhc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fhc *FileHashCreate) Exec(ctx context.Context) error {
	_, err := fhc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fhc *FileHashCreate) ExecX(ctx context.Context) {
	if err := fhc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fhc *FileHashCreate) defaults() {
	if _, ok := fhc.mutation.ReferenceCount(); !ok {
		v := filehash.DefaultReferenceCount
		fhc.mutation.SetReferenceCount(v)
	}
	if _, ok := fhc.mutation.CreatedAt(); !ok {
		v := filehash.DefaultCreatedAt()
		fhc.mutation.SetCreatedAt(v)
	}
	if _, ok := fhc.mutation.UpdatedAt(); !ok {
		v := filehash.DefaultUpdatedAt()
		fhc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fhc *FileHashCreate) check() error {
	if _, ok := fhc.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "FileHash.hash"`)}
	}
	if v, ok := fhc.mutation.Hash(); ok {
		if err := filehash.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "FileHash.hash": %w`, err)}
		}
	}
	if _, ok := fhc.mutation.MinioObject(); !ok {
		return &ValidationError{Name: "minio_object", err: errors.New(`ent: missing required field "FileHash.minio_object"`)}
	}
	if v, ok := fhc.mutation.MinioObject(); ok {
		if err := filehash.MinioObjectValidator(v); err != nil {
			return &ValidationError{Name: "minio_object", err: fmt.Errorf(`ent: validator failed for field "FileHash.minio_object": %w`, err)}
		}
	}
	if _, ok := fhc.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "FileHash.size"`)}
	}
	if _, ok := fhc.mutation.ReferenceCount(); !ok {
		return &ValidationError{Name: "reference_count", err: errors.New(`ent: missing required field "FileHash.reference_count"`)}
	}
	if _, ok := fhc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FileHash.created_at"`)}
	}
	if _, ok := fhc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FileHash.updated_at"`)}
	}
	return nil
}

func (fhc *FileHashCreate) sqlSave(ctx context.Context) (*FileHash, error) {
	if err := fhc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fhc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fhc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fhc.mutation.id = &_node.ID
	fhc.mutation.done = true
	return _node, nil
}

func (fhc *FileHashCreate) createSpec() (*FileHash, *sqlgraph.CreateSpec) {
	var (
		_node = &FileHash{config: fhc.config}
		_spec = sqlgraph.NewCreateSpec(filehash.Table, sqlgraph.NewFieldSpec(filehash.FieldID, field.TypeInt))
	)
	if value, ok := fhc.mutation.Hash(); ok {
		_spec.SetField(filehash.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := fhc.mutation.MinioObject(); ok {
		_spec.SetField(filehash.FieldMinioObject, field.TypeString, value)
		_node.MinioObject = value
	}
	if value, ok := fhc.mutation.Size(); ok {
		_spec.SetField(filehash.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := fhc.mutation.MimeType(); ok {
		_spec.SetField(filehash.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := fhc.mutation.ReferenceCount(); ok {
		_spec.SetField(filehash.FieldReferenceCount, field.TypeInt, value)
		_node.ReferenceCount = value
	}
	if value, ok := fhc.mutation.CreatedAt(); ok {
		_spec.SetField(filehash.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fhc.mutation.UpdatedAt(); ok {
		_spec.SetField(filehash.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// FileHashCreateBulk is the builder for creating many FileHash entities in bulk.
type FileHashCreateBulk struct {
	config
	err      error
	builders []*FileHashCreate
}

// Save creates the FileHash entities in the database.
func (fhcb *FileHashCreateBulk) Save(ctx context.Context) ([]*FileHash, error) {
	if fhcb.err != nil {
		return nil, fhcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fhcb.builders))
	nodes := make([]*FileHash, len(fhcb.builders))
	mutators := make([]Mutator, len(fhcb.builders))
	for i := range fhcb.builders {
		func(i int, root context.Context) {
			builder := fhcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileHashMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fhcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fhcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fhcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fhcb *FileHashCreateBulk) SaveX(ctx context.Context) []*FileHash {
	v, err := fhcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fhcb *FileHashCreateBulk) Exec(ctx context.Context) error {
	_, err := fhcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fhcb *FileHashCreateBulk) ExecX(ctx context.Context) {
	if err := fhcb.Exec(ctx); err != nil {
		panic(err)
	}
}
