// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gopan-server/ent/filehash"
	"gopan-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileHashDelete is the builder for deleting a FileHash entity.
type FileHashDelete struct {
	config
	hooks    []Hook
	mutation *FileHashMutation
}

// Where appends a list predicates to the FileHashDelete builder.
func (fhd *FileHashDelete) Where(ps ...predicate.FileHash) *FileHashDelete {
	fhd.mutation.Where(ps...)
	return fhd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fhd *FileHashDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fhd.sqlExec, fhd.mutation, fhd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fhd *FileHashDelete) ExecX(ctx context.Context) int {
	n, err := fhd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fhd *FileHashDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(filehash.Table, sqlgraph.NewFieldSpec(filehash.FieldID, field.TypeInt))
	if ps := fhd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fhd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fhd.mutation.done = true
	return affected, err
}

// FileHashDeleteOne is the builder for deleting a single FileHash entity.
type FileHashDeleteOne struct {
	fhd *FileHashDelete
}

// Where appends a list predicates to the FileHashDelete builder.
func (fhdo *FileHashDeleteOne) Where(ps ...predicate.FileHash) *FileHashDeleteOne {
	fhdo.fhd.mutation.Where(ps...)
	return fhdo
}

// Exec executes the deletion query.
func (fhdo *FileHashDeleteOne) Exec(ctx context.Context) error {
	n, err := fhdo.fhd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{filehash.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fhdo *FileHashDeleteOne) ExecX(ctx context.Context) {
	if err := fhdo.Exec(ctx); err != nil {
		panic(err)
	}
}
