// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gopan-server/ent/filehash"
	"gopan-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileHashUpdate is the builder for updating FileHash entities.
type FileHashUpdate struct {
	config
	hooks    []Hook
	mutation *FileHashMutation
}

// Where appends a list predicates to the FileHashUpdate builder.
func (fhu *FileHashUpdate) Where(ps ...predicate.FileHash) *FileHashUpdate {
	fhu.mutation.Where(ps...)
	return fhu
}

// SetHash sets the "hash" field.
func (fhu *FileHashUpdate) SetHash(s string) *FileHashUpdate {
	fhu.mutation.SetHash(s)
	return fhu
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (fhu *FileHashUpdate) SetNillableHash(s *string) *FileHashUpdate {
	if s != nil {
		fhu.SetHash(*s)
	}
	return fhu
}

// SetMinioObject sets the "minio_object" field.
func (fhu *FileHashUpdate) SetMinioObject(s string) *FileHashUpdate {
	fhu.mutation.SetMinioObject(s)
	return fhu
}

// SetNillableMinioObject sets the "minio_object" field if the given value is not nil.
func (fhu *FileHashUpdate) SetNillableMinioObject(s *string) *FileHashUpdate {
	if s != nil {
		fhu.SetMinioObject(*s)
	}
	return fhu
}

// SetSize sets the "size" field.
func (fhu *FileHashUpdate) SetSize(i int64) *FileHashUpdate {
	fhu.mutation.ResetSize()
	fhu.mutation.SetSize(i)
	return fhu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (fhu *FileHashUpdate) SetNillableSize(i *int64) *FileHashUpdate {
	if i != nil {
		fhu.SetSize(*i)
	}
	return fhu
}

// AddSize adds i to the "size" field.
func (fhu *FileHashUpdate) AddSize(i int64) *FileHashUpdate {
	fhu.mutation.AddSize(i)
	return fhu
}

// SetMimeType sets the "mime_type" field.
func (fhu *FileHashUpdate) SetMimeType(s string) *FileHashUpdate {
	fhu.mutation.SetMimeType(s)
	return fhu
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (fhu *FileHashUpdate) SetNillableMimeType(s *string) *FileHashUpdate {
	if s != nil {
		fhu.SetMimeType(*s)
	}
	return fhu
}

// ClearMimeType clears the value of the "mime_type" field.
func (fhu *FileHashUpdate) ClearMimeType() *FileHashUpdate {
	fhu.mutation.ClearMimeType()
	return fhu
}

// SetReferenceCount sets the "reference_count" field.
func (fhu *FileHashUpdate) SetReferenceCount(i int) *FileHashUpdate {
	fhu.mutation.ResetReferenceCount()
	fhu.mutation.SetReferenceCount(i)
	return fhu
}

// SetNillableReferenceCount sets the "reference_count" field if the given value is not nil.
func (fhu *FileHashUpdate) SetNillableReferenceCount(i *int) *FileHashUpdate {
	if i != nil {
		fhu.SetReferenceCount(*i)
	}
	return fhu
}

// AddReferenceCount adds i to the "reference_count" field.
func (fhu *FileHashUpdate) AddReferenceCount(i int) *FileHashUpdate {
	fhu.mutation.AddReferenceCount(i)
	return fhu
}

// SetCreatedAt sets the "created_at" field.
func (fhu *FileHashUpdate) SetCreatedAt(t time.Time) *FileHashUpdate {
	fhu.mutation.SetCreatedAt(t)
	return fhu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fhu *FileHashUpdate) SetNillableCreatedAt(t *time.Time) *FileHashUpdate {
	if t != nil {
		fhu.SetCreatedAt(*t)
	}
	return fhu
}

// SetUpdatedAt sets the "updated_at" field.
func (fhu *FileHashUpdate) SetUpdatedAt(t time.Time) *FileHashUpdate {
	fhu.mutation.SetUpdatedAt(t)
	return fhu
}

// Mutation returns the FileHashMutation object of the builder.
func (fhu *FileHashUpdate) Mutation() *FileHashMutation {
	return fhu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fhu *FileHashUpdate) Save(ctx context.Context) (int, error) {
	fhu.defaults()
	return withHooks(ctx, fhu.sqlSave, fhu.mutation, fhu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fhu *FileHashUpdate) SaveX(ctx context.Context) int {
	affected, err := fhu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fhu *FileHashUpdate) Exec(ctx context.Context) error {
	_, err := fhu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fhu *FileHashUpdate) ExecX(ctx context.Context) {
	if err := fhu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fhu *FileHashUpdate) defaults() {
	if _, ok := fhu.mutation.UpdatedAt(); !ok {
		v := filehash.UpdateDefaultUpdatedAt()
		fhu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fhu *FileHashUpdate) check() error {
	if v, ok := fhu.mutation.Hash(); ok {
		if err := filehash.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "FileHash.hash": %w`, err)}
		}
	}
	if v, ok := fhu.mutation.MinioObject(); ok {
		if err := filehash.MinioObjectValidator(v); err != nil {
			return &ValidationError{Name: "minio_object", err: fmt.Errorf(`ent: validator failed for field "FileHash.minio_object": %w`, err)}
		}
	}
	return nil
}

func (fhu *FileHashUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fhu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(filehash.Table, filehash.Columns, sqlgraph.NewFieldSpec(filehash.FieldID, field.TypeInt))
	if ps := fhu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fhu.mutation.Hash(); ok {
		_spec.SetField(filehash.FieldHash, field.TypeString, value)
	}
	if value, ok := fhu.mutation.MinioObject(); ok {
		_spec.SetField(filehash.FieldMinioObject, field.TypeString, value)
	}
	if value, ok := fhu.mutation.Size(); ok {
		_spec.SetField(filehash.FieldSize, field.TypeInt64, value)
	}
	if value, ok := fhu.mutation.AddedSize(); ok {
		_spec.AddField(filehash.FieldSize, field.TypeInt64, value)
	}
	if value, ok := fhu.mutation.MimeType(); ok {
		_spec.SetField(filehash.FieldMimeType, field.TypeString, value)
	}
	if fhu.mutation.MimeTypeCleared() {
		_spec.ClearField(filehash.FieldMimeType, field.TypeString)
	}
	if value, ok := fhu.mutation.ReferenceCount(); ok {
		_spec.SetField(filehash.FieldReferenceCount, field.TypeInt, value)
	}
	if value, ok := fhu.mutation.AddedReferenceCount(); ok {
		_spec.AddField(filehash.FieldReferenceCount, field.TypeInt, value)
	}
	if value, ok := fhu.mutation.CreatedAt(); ok {
		_spec.SetField(filehash.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := fhu.mutation.UpdatedAt(); ok {
		_spec.SetField(filehash.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fhu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filehash.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fhu.mutation.done = true
	return n, nil
}

// FileHashUpdateOne is the builder for updating a single FileHash entity.
type FileHashUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileHashMutation
}

// SetHash sets the "hash" field.
func (fhuo *FileHashUpdateOne) SetHash(s string) *FileHashUpdateOne {
	fhuo.mutation.SetHash(s)
	return fhuo
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (fhuo *FileHashUpdateOne) SetNillableHash(s *string) *FileHashUpdateOne {
	if s != nil {
		fhuo.SetHash(*s)
	}
	return fhuo
}

// SetMinioObject sets the "minio_object" field.
func (fhuo *FileHashUpdateOne) SetMinioObject(s string) *FileHashUpdateOne {
	fhuo.mutation.SetMinioObject(s)
	return fhuo
}

// SetNillableMinioObject sets the "minio_object" field if the given value is not nil.
func (fhuo *FileHashUpdateOne) SetNillableMinioObject(s *string) *FileHashUpdateOne {
	if s != nil {
		fhuo.SetMinioObject(*s)
	}
	return fhuo
}

// SetSize sets the "size" field.
func (fhuo *FileHashUpdateOne) SetSize(i int64) *FileHashUpdateOne {
	fhuo.mutation.ResetSize()
	fhuo.mutation.SetSize(i)
	return fhuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (fhuo *FileHashUpdateOne) SetNillableSize(i *int64) *FileHashUpdateOne {
	if i != nil {
		fhuo.SetSize(*i)
	}
	return fhuo
}

// AddSize adds i to the "size" field.
func (fhuo *FileHashUpdateOne) AddSize(i int64) *FileHashUpdateOne {
	fhuo.mutation.AddSize(i)
	return fhuo
}

// SetMimeType sets the "mime_type" field.
func (fhuo *FileHashUpdateOne) SetMimeType(s string) *FileHashUpdateOne {
	fhuo.mutation.SetMimeType(s)
	return fhuo
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (fhuo *FileHashUpdateOne) SetNillableMimeType(s *string) *FileHashUpdateOne {
	if s != nil {
		fhuo.SetMimeType(*s)
	}
	return fhuo
}

// ClearMimeType clears the value of the "mime_type" field.
func (fhuo *FileHashUpdateOne) ClearMimeType() *FileHashUpdateOne {
	fhuo.mutation.ClearMimeType()
	return fhuo
}

// SetReferenceCount sets the "reference_count" field.
func (fhuo *FileHashUpdateOne) SetReferenceCount(i int) *FileHashUpdateOne {
	fhuo.mutation.ResetReferenceCount()
	fhuo.mutation.SetReferenceCount(i)
	return fhuo
}

// SetNillableReferenceCount sets the "reference_count" field if the given value is not nil.
func (fhuo *FileHashUpdateOne) SetNillableReferenceCount(i *int) *FileHashUpdateOne {
	if i != nil {
		fhuo.SetReferenceCount(*i)
	}
	return fhuo
}

// AddReferenceCount adds i to the "reference_count" field.
func (fhuo *FileHashUpdateOne) AddReferenceCount(i int) *FileHashUpdateOne {
	fhuo.mutation.AddReferenceCount(i)
	return fhuo
}

// SetCreatedAt sets the "created_at" field.
func (fhuo *FileHashUpdateOne) SetCreatedAt(t time.Time) *FileHashUpdateOne {
	fhuo.mutation.SetCreatedAt(t)
	return fhuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fhuo *FileHashUpdateOne) SetNillableCreatedAt(t *time.Time) *FileHashUpdateOne {
	if t != nil {
		fhuo.SetCreatedAt(*t)
	}
	return fhuo
}

// SetUpdatedAt sets the "updated_at" field.
func (fhuo *FileHashUpdateOne) SetUpdatedAt(t time.Time) *FileHashUpdateOne {
	fhuo.mutation.SetUpdatedAt(t)
	return fhuo
}

// Mutation returns the FileHashMutation object of the builder.
func (fhuo *FileHashUpdateOne) Mutation() *FileHashMutation {
	return fhuo.mutation
}

// Where appends a list predicates to the FileHashUpdate builder.
func (fhuo *FileHashUpdateOne) Where(ps ...predicate.FileHash) *FileHashUpdateOne {
	fhuo.mutation.Where(ps...)
	return fhuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fhuo *FileHashUpdateOne) Select(field string, fields ...string) *FileHashUpdateOne {
	fhuo.fields = append([]string{field}, fields...)
	return fhuo
}

// Save executes the query and returns the updated FileHash entity.
func (fhuo *FileHashUpdateOne) Save(ctx context.Context) (*FileHash, error) {
	fhuo.defaults()
	return withHooks(ctx, fhuo.sqlSave, fhuo.mutation, fhuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fhuo *FileHashUpdateOne) SaveX(ctx context.Context) *FileHash {
	node, err := fhuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fhuo *FileHashUpdateOne) Exec(ctx context.Context) error {
	_, err := fhuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fhuo *FileHashUpdateOne) ExecX(ctx context.Context) {
	if err := fhuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fhuo *FileHashUpdateOne) defaults() {
	if _, ok := fhuo.mutation.UpdatedAt(); !ok {
		v := filehash.UpdateDefaultUpdatedAt()
		fhuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fhuo *FileHashUpdateOne) check() error {
	if v, ok := fhuo.mutation.Hash(); ok {
		if err := filehash.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "FileHash.hash": %w`, err)}
		}
	}
	if v, ok := fhuo.mutation.MinioObject(); ok {
		if err := filehash.MinioObjectValidator(v); err != nil {
			return &ValidationError{Name: "minio_object", err: fmt.Errorf(`ent: validator failed for field "FileHash.minio_object": %w`, err)}
		}
	}
	return nil
}

func (fhuo *FileHashUpdateOne) sqlSave(ctx context.Context) (_node *FileHash, err error) {
	if err := fhuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filehash.Table, filehash.Columns, sqlgraph.NewFieldSpec(filehash.FieldID, field.TypeInt))
	id, ok := fhuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileHash.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fhuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filehash.FieldID)
		for _, f := range fields {
			if !filehash.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != filehash.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fhuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fhuo.mutation.Hash(); ok {
		_spec.SetField(filehash.FieldHash, field.TypeString, value)
	}
	if value, ok := fhuo.mutation.MinioObject(); ok {
		_spec.SetField(filehash.FieldMinioObject, field.TypeString, value)
	}
	if value, ok := fhuo.mutation.Size(); ok {
		_spec.SetField(filehash.FieldSize, field.TypeInt64, value)
	}
	if value, ok := fhuo.mutation.AddedSize(); ok {
		_spec.AddField(filehash.FieldSize, field.TypeInt64, value)
	}
	if value, ok := fhuo.mutation.MimeType(); ok {
		_spec.SetField(filehash.FieldMimeType, field.TypeString, value)
	}
	if fhuo.mutation.MimeTypeCleared() {
		_spec.ClearField(filehash.FieldMimeType, field.TypeString)
	}
	if value, ok := fhuo.mutation.ReferenceCount(); ok {
		_spec.SetField(filehash.FieldReferenceCount, field.TypeInt, value)
	}
	if value, ok := fhuo.mutation.AddedReferenceCount(); ok {
		_spec.AddField(filehash.FieldReferenceCount, field.TypeInt, value)
	}
	if value, ok := fhuo.mutation.CreatedAt(); ok {
		_spec.SetField(filehash.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := fhuo.mutation.UpdatedAt(); ok {
		_spec.SetField(filehash.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FileHash{config: fhuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fhuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filehash.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fhuo.mutation.done = true
	return _node, nil
}
