// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gopan-server/ent/node"
	"gopan-server/ent/predicate"
	"gopan-server/ent/share"
	"gopan-server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (nu *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetName sets the "name" field.
func (nu *NodeUpdate) SetName(s string) *NodeUpdate {
	nu.mutation.SetName(s)
	return nu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableName(s *string) *NodeUpdate {
	if s != nil {
		nu.SetName(*s)
	}
	return nu
}

// SetType sets the "type" field.
func (nu *NodeUpdate) SetType(i int) *NodeUpdate {
	nu.mutation.ResetType()
	nu.mutation.SetType(i)
	return nu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableType(i *int) *NodeUpdate {
	if i != nil {
		nu.SetType(*i)
	}
	return nu
}

// AddType adds i to the "type" field.
func (nu *NodeUpdate) AddType(i int) *NodeUpdate {
	nu.mutation.AddType(i)
	return nu
}

// SetSize sets the "size" field.
func (nu *NodeUpdate) SetSize(i int64) *NodeUpdate {
	nu.mutation.ResetSize()
	nu.mutation.SetSize(i)
	return nu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableSize(i *int64) *NodeUpdate {
	if i != nil {
		nu.SetSize(*i)
	}
	return nu
}

// AddSize adds i to the "size" field.
func (nu *NodeUpdate) AddSize(i int64) *NodeUpdate {
	nu.mutation.AddSize(i)
	return nu
}

// SetMimeType sets the "mime_type" field.
func (nu *NodeUpdate) SetMimeType(s string) *NodeUpdate {
	nu.mutation.SetMimeType(s)
	return nu
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableMimeType(s *string) *NodeUpdate {
	if s != nil {
		nu.SetMimeType(*s)
	}
	return nu
}

// ClearMimeType clears the value of the "mime_type" field.
func (nu *NodeUpdate) ClearMimeType() *NodeUpdate {
	nu.mutation.ClearMimeType()
	return nu
}

// SetFileHash sets the "file_hash" field.
func (nu *NodeUpdate) SetFileHash(s string) *NodeUpdate {
	nu.mutation.SetFileHash(s)
	return nu
}

// SetNillableFileHash sets the "file_hash" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableFileHash(s *string) *NodeUpdate {
	if s != nil {
		nu.SetFileHash(*s)
	}
	return nu
}

// ClearFileHash clears the value of the "file_hash" field.
func (nu *NodeUpdate) ClearFileHash() *NodeUpdate {
	nu.mutation.ClearFileHash()
	return nu
}

// SetMinioObject sets the "minio_object" field.
func (nu *NodeUpdate) SetMinioObject(s string) *NodeUpdate {
	nu.mutation.SetMinioObject(s)
	return nu
}

// SetNillableMinioObject sets the "minio_object" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableMinioObject(s *string) *NodeUpdate {
	if s != nil {
		nu.SetMinioObject(*s)
	}
	return nu
}

// ClearMinioObject clears the value of the "minio_object" field.
func (nu *NodeUpdate) ClearMinioObject() *NodeUpdate {
	nu.mutation.ClearMinioObject()
	return nu
}

// SetIsDeleted sets the "is_deleted" field.
func (nu *NodeUpdate) SetIsDeleted(b bool) *NodeUpdate {
	nu.mutation.SetIsDeleted(b)
	return nu
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableIsDeleted(b *bool) *NodeUpdate {
	if b != nil {
		nu.SetIsDeleted(*b)
	}
	return nu
}

// SetDeletedAt sets the "deleted_at" field.
func (nu *NodeUpdate) SetDeletedAt(t time.Time) *NodeUpdate {
	nu.mutation.SetDeletedAt(t)
	return nu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableDeletedAt(t *time.Time) *NodeUpdate {
	if t != nil {
		nu.SetDeletedAt(*t)
	}
	return nu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (nu *NodeUpdate) ClearDeletedAt() *NodeUpdate {
	nu.mutation.ClearDeletedAt()
	return nu
}

// SetCreatedAt sets the "created_at" field.
func (nu *NodeUpdate) SetCreatedAt(t time.Time) *NodeUpdate {
	nu.mutation.SetCreatedAt(t)
	return nu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableCreatedAt(t *time.Time) *NodeUpdate {
	if t != nil {
		nu.SetCreatedAt(*t)
	}
	return nu
}

// SetUpdatedAt sets the "updated_at" field.
func (nu *NodeUpdate) SetUpdatedAt(t time.Time) *NodeUpdate {
	nu.mutation.SetUpdatedAt(t)
	return nu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (nu *NodeUpdate) SetOwnerID(id int) *NodeUpdate {
	nu.mutation.SetOwnerID(id)
	return nu
}

// SetOwner sets the "owner" edge to the User entity.
func (nu *NodeUpdate) SetOwner(u *User) *NodeUpdate {
	return nu.SetOwnerID(u.ID)
}

// SetParentID sets the "parent" edge to the Node entity by ID.
func (nu *NodeUpdate) SetParentID(id int) *NodeUpdate {
	nu.mutation.SetParentID(id)
	return nu
}

// SetNillableParentID sets the "parent" edge to the Node entity by ID if the given value is not nil.
func (nu *NodeUpdate) SetNillableParentID(id *int) *NodeUpdate {
	if id != nil {
		nu = nu.SetParentID(*id)
	}
	return nu
}

// SetParent sets the "parent" edge to the Node entity.
func (nu *NodeUpdate) SetParent(n *Node) *NodeUpdate {
	return nu.SetParentID(n.ID)
}

// AddChildIDs adds the "children" edge to the Node entity by IDs.
func (nu *NodeUpdate) AddChildIDs(ids ...int) *NodeUpdate {
	nu.mutation.AddChildIDs(ids...)
	return nu
}

// AddChildren adds the "children" edges to the Node entity.
func (nu *NodeUpdate) AddChildren(n ...*Node) *NodeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.AddChildIDs(ids...)
}

// AddShareIDs adds the "shares" edge to the Share entity by IDs.
func (nu *NodeUpdate) AddShareIDs(ids ...int) *NodeUpdate {
	nu.mutation.AddShareIDs(ids...)
	return nu
}

// AddShares adds the "shares" edges to the Share entity.
func (nu *NodeUpdate) AddShares(s ...*Share) *NodeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return nu.AddShareIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nu *NodeUpdate) Mutation() *NodeMutation {
	return nu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (nu *NodeUpdate) ClearOwner() *NodeUpdate {
	nu.mutation.ClearOwner()
	return nu
}

// ClearParent clears the "parent" edge to the Node entity.
func (nu *NodeUpdate) ClearParent() *NodeUpdate {
	nu.mutation.ClearParent()
	return nu
}

// ClearChildren clears all "children" edges to the Node entity.
func (nu *NodeUpdate) ClearChildren() *NodeUpdate {
	nu.mutation.ClearChildren()
	return nu
}

// RemoveChildIDs removes the "children" edge to Node entities by IDs.
func (nu *NodeUpdate) RemoveChildIDs(ids ...int) *NodeUpdate {
	nu.mutation.RemoveChildIDs(ids...)
	return nu
}

// RemoveChildren removes "children" edges to Node entities.
func (nu *NodeUpdate) RemoveChildren(n ...*Node) *NodeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.RemoveChildIDs(ids...)
}

// ClearShares clears all "shares" edges to the Share entity.
func (nu *NodeUpdate) ClearShares() *NodeUpdate {
	nu.mutation.ClearShares()
	return nu
}

// RemoveShareIDs removes the "shares" edge to Share entities by IDs.
func (nu *NodeUpdate) RemoveShareIDs(ids ...int) *NodeUpdate {
	nu.mutation.RemoveShareIDs(ids...)
	return nu
}

// RemoveShares removes "shares" edges to Share entities.
func (nu *NodeUpdate) RemoveShares(s ...*Share) *NodeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return nu.RemoveShareIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NodeUpdate) Save(ctx context.Context) (int, error) {
	nu.defaults()
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NodeUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NodeUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NodeUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NodeUpdate) check() error {
	if v, ok := nu.mutation.Name(); ok {
		if err := node.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Node.name": %w`, err)}
		}
	}
	if nu.mutation.OwnerCleared() && len(nu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Node.owner"`)
	}
	return nil
}

func (nu *NodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := nu.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeInt, value)
	}
	if value, ok := nu.mutation.AddedType(); ok {
		_spec.AddField(node.FieldType, field.TypeInt, value)
	}
	if value, ok := nu.mutation.Size(); ok {
		_spec.SetField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.AddedSize(); ok {
		_spec.AddField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.MimeType(); ok {
		_spec.SetField(node.FieldMimeType, field.TypeString, value)
	}
	if nu.mutation.MimeTypeCleared() {
		_spec.ClearField(node.FieldMimeType, field.TypeString)
	}
	if value, ok := nu.mutation.FileHash(); ok {
		_spec.SetField(node.FieldFileHash, field.TypeString, value)
	}
	if nu.mutation.FileHashCleared() {
		_spec.ClearField(node.FieldFileHash, field.TypeString)
	}
	if value, ok := nu.mutation.MinioObject(); ok {
		_spec.SetField(node.FieldMinioObject, field.TypeString, value)
	}
	if nu.mutation.MinioObjectCleared() {
		_spec.ClearField(node.FieldMinioObject, field.TypeString)
	}
	if value, ok := nu.mutation.IsDeleted(); ok {
		_spec.SetField(node.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := nu.mutation.DeletedAt(); ok {
		_spec.SetField(node.FieldDeletedAt, field.TypeTime, value)
	}
	if nu.mutation.DeletedAtCleared() {
		_spec.ClearField(node.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := nu.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if nu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.OwnerTable,
			Columns: []string{node.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.OwnerTable,
			Columns: []string{node.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !nu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SharesTable,
			Columns: []string{node.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedSharesIDs(); len(nodes) > 0 && !nu.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SharesTable,
			Columns: []string{node.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SharesTable,
			Columns: []string{node.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetName sets the "name" field.
func (nuo *NodeUpdateOne) SetName(s string) *NodeUpdateOne {
	nuo.mutation.SetName(s)
	return nuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableName(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetName(*s)
	}
	return nuo
}

// SetType sets the "type" field.
func (nuo *NodeUpdateOne) SetType(i int) *NodeUpdateOne {
	nuo.mutation.ResetType()
	nuo.mutation.SetType(i)
	return nuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableType(i *int) *NodeUpdateOne {
	if i != nil {
		nuo.SetType(*i)
	}
	return nuo
}

// AddType adds i to the "type" field.
func (nuo *NodeUpdateOne) AddType(i int) *NodeUpdateOne {
	nuo.mutation.AddType(i)
	return nuo
}

// SetSize sets the "size" field.
func (nuo *NodeUpdateOne) SetSize(i int64) *NodeUpdateOne {
	nuo.mutation.ResetSize()
	nuo.mutation.SetSize(i)
	return nuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableSize(i *int64) *NodeUpdateOne {
	if i != nil {
		nuo.SetSize(*i)
	}
	return nuo
}

// AddSize adds i to the "size" field.
func (nuo *NodeUpdateOne) AddSize(i int64) *NodeUpdateOne {
	nuo.mutation.AddSize(i)
	return nuo
}

// SetMimeType sets the "mime_type" field.
func (nuo *NodeUpdateOne) SetMimeType(s string) *NodeUpdateOne {
	nuo.mutation.SetMimeType(s)
	return nuo
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableMimeType(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetMimeType(*s)
	}
	return nuo
}

// ClearMimeType clears the value of the "mime_type" field.
func (nuo *NodeUpdateOne) ClearMimeType() *NodeUpdateOne {
	nuo.mutation.ClearMimeType()
	return nuo
}

// SetFileHash sets the "file_hash" field.
func (nuo *NodeUpdateOne) SetFileHash(s string) *NodeUpdateOne {
	nuo.mutation.SetFileHash(s)
	return nuo
}

// SetNillableFileHash sets the "file_hash" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableFileHash(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetFileHash(*s)
	}
	return nuo
}

// ClearFileHash clears the value of the "file_hash" field.
func (nuo *NodeUpdateOne) ClearFileHash() *NodeUpdateOne {
	nuo.mutation.ClearFileHash()
	return nuo
}

// SetMinioObject sets the "minio_object" field.
func (nuo *NodeUpdateOne) SetMinioObject(s string) *NodeUpdateOne {
	nuo.mutation.SetMinioObject(s)
	return nuo
}

// SetNillableMinioObject sets the "minio_object" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableMinioObject(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetMinioObject(*s)
	}
	return nuo
}

// ClearMinioObject clears the value of the "minio_object" field.
func (nuo *NodeUpdateOne) ClearMinioObject() *NodeUpdateOne {
	nuo.mutation.ClearMinioObject()
	return nuo
}

// SetIsDeleted sets the "is_deleted" field.
func (nuo *NodeUpdateOne) SetIsDeleted(b bool) *NodeUpdateOne {
	nuo.mutation.SetIsDeleted(b)
	return nuo
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableIsDeleted(b *bool) *NodeUpdateOne {
	if b != nil {
		nuo.SetIsDeleted(*b)
	}
	return nuo
}

// SetDeletedAt sets the "deleted_at" field.
func (nuo *NodeUpdateOne) SetDeletedAt(t time.Time) *NodeUpdateOne {
	nuo.mutation.SetDeletedAt(t)
	return nuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableDeletedAt(t *time.Time) *NodeUpdateOne {
	if t != nil {
		nuo.SetDeletedAt(*t)
	}
	return nuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (nuo *NodeUpdateOne) ClearDeletedAt() *NodeUpdateOne {
	nuo.mutation.ClearDeletedAt()
	return nuo
}

// SetCreatedAt sets the "created_at" field.
func (nuo *NodeUpdateOne) SetCreatedAt(t time.Time) *NodeUpdateOne {
	nuo.mutation.SetCreatedAt(t)
	return nuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableCreatedAt(t *time.Time) *NodeUpdateOne {
	if t != nil {
		nuo.SetCreatedAt(*t)
	}
	return nuo
}

// SetUpdatedAt sets the "updated_at" field.
func (nuo *NodeUpdateOne) SetUpdatedAt(t time.Time) *NodeUpdateOne {
	nuo.mutation.SetUpdatedAt(t)
	return nuo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (nuo *NodeUpdateOne) SetOwnerID(id int) *NodeUpdateOne {
	nuo.mutation.SetOwnerID(id)
	return nuo
}

// SetOwner sets the "owner" edge to the User entity.
func (nuo *NodeUpdateOne) SetOwner(u *User) *NodeUpdateOne {
	return nuo.SetOwnerID(u.ID)
}

// SetParentID sets the "parent" edge to the Node entity by ID.
func (nuo *NodeUpdateOne) SetParentID(id int) *NodeUpdateOne {
	nuo.mutation.SetParentID(id)
	return nuo
}

// SetNillableParentID sets the "parent" edge to the Node entity by ID if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableParentID(id *int) *NodeUpdateOne {
	if id != nil {
		nuo = nuo.SetParentID(*id)
	}
	return nuo
}

// SetParent sets the "parent" edge to the Node entity.
func (nuo *NodeUpdateOne) SetParent(n *Node) *NodeUpdateOne {
	return nuo.SetParentID(n.ID)
}

// AddChildIDs adds the "children" edge to the Node entity by IDs.
func (nuo *NodeUpdateOne) AddChildIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.AddChildIDs(ids...)
	return nuo
}

// AddChildren adds the "children" edges to the Node entity.
func (nuo *NodeUpdateOne) AddChildren(n ...*Node) *NodeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.AddChildIDs(ids...)
}

// AddShareIDs adds the "shares" edge to the Share entity by IDs.
func (nuo *NodeUpdateOne) AddShareIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.AddShareIDs(ids...)
	return nuo
}

// AddShares adds the "shares" edges to the Share entity.
func (nuo *NodeUpdateOne) AddShares(s ...*Share) *NodeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return nuo.AddShareIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nuo *NodeUpdateOne) Mutation() *NodeMutation {
	return nuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (nuo *NodeUpdateOne) ClearOwner() *NodeUpdateOne {
	nuo.mutation.ClearOwner()
	return nuo
}

// ClearParent clears the "parent" edge to the Node entity.
func (nuo *NodeUpdateOne) ClearParent() *NodeUpdateOne {
	nuo.mutation.ClearParent()
	return nuo
}

// ClearChildren clears all "children" edges to the Node entity.
func (nuo *NodeUpdateOne) ClearChildren() *NodeUpdateOne {
	nuo.mutation.ClearChildren()
	return nuo
}

// RemoveChildIDs removes the "children" edge to Node entities by IDs.
func (nuo *NodeUpdateOne) RemoveChildIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.RemoveChildIDs(ids...)
	return nuo
}

// RemoveChildren removes "children" edges to Node entities.
func (nuo *NodeUpdateOne) RemoveChildren(n ...*Node) *NodeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.RemoveChildIDs(ids...)
}

// ClearShares clears all "shares" edges to the Share entity.
func (nuo *NodeUpdateOne) ClearShares() *NodeUpdateOne {
	nuo.mutation.ClearShares()
	return nuo
}

// RemoveShareIDs removes the "shares" edge to Share entities by IDs.
func (nuo *NodeUpdateOne) RemoveShareIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.RemoveShareIDs(ids...)
	return nuo
}

// RemoveShares removes "shares" edges to Share entities.
func (nuo *NodeUpdateOne) RemoveShares(s ...*Share) *NodeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return nuo.RemoveShareIDs(ids...)
}

// Where appends a list predicates to the NodeUpdate builder.
func (nuo *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Node entity.
func (nuo *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	nuo.defaults()
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NodeUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NodeUpdateOne) check() error {
	if v, ok := nuo.mutation.Name(); ok {
		if err := node.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Node.name": %w`, err)}
		}
	}
	if nuo.mutation.OwnerCleared() && len(nuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Node.owner"`)
	}
	return nil
}

func (nuo *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := nuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := nuo.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeInt, value)
	}
	if value, ok := nuo.mutation.AddedType(); ok {
		_spec.AddField(node.FieldType, field.TypeInt, value)
	}
	if value, ok := nuo.mutation.Size(); ok {
		_spec.SetField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.AddedSize(); ok {
		_spec.AddField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.MimeType(); ok {
		_spec.SetField(node.FieldMimeType, field.TypeString, value)
	}
	if nuo.mutation.MimeTypeCleared() {
		_spec.ClearField(node.FieldMimeType, field.TypeString)
	}
	if value, ok := nuo.mutation.FileHash(); ok {
		_spec.SetField(node.FieldFileHash, field.TypeString, value)
	}
	if nuo.mutation.FileHashCleared() {
		_spec.ClearField(node.FieldFileHash, field.TypeString)
	}
	if value, ok := nuo.mutation.MinioObject(); ok {
		_spec.SetField(node.FieldMinioObject, field.TypeString, value)
	}
	if nuo.mutation.MinioObjectCleared() {
		_spec.ClearField(node.FieldMinioObject, field.TypeString)
	}
	if value, ok := nuo.mutation.IsDeleted(); ok {
		_spec.SetField(node.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := nuo.mutation.DeletedAt(); ok {
		_spec.SetField(node.FieldDeletedAt, field.TypeTime, value)
	}
	if nuo.mutation.DeletedAtCleared() {
		_spec.ClearField(node.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := nuo.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if nuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.OwnerTable,
			Columns: []string{node.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.OwnerTable,
			Columns: []string{node.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !nuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SharesTable,
			Columns: []string{node.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedSharesIDs(); len(nodes) > 0 && !nuo.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SharesTable,
			Columns: []string{node.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SharesTable,
			Columns: []string{node.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
