// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gopan-server/ent/filehash"
	"gopan-server/ent/node"
	"gopan-server/ent/schema"
	"gopan-server/ent/share"
	"gopan-server/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	filehashFields := schema.FileHash{}.Fields()
	_ = filehashFields
	// filehashDescHash is the schema descriptor for hash field.
	filehashDescHash := filehashFields[0].Descriptor()
	// filehash.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	filehash.HashValidator = filehashDescHash.Validators[0].(func(string) error)
	// filehashDescMinioObject is the schema descriptor for minio_object field.
	filehashDescMinioObject := filehashFields[1].Descriptor()
	// filehash.MinioObjectValidator is a validator for the "minio_object" field. It is called by the builders before save.
	filehash.MinioObjectValidator = filehashDescMinioObject.Validators[0].(func(string) error)
	// filehashDescReferenceCount is the schema descriptor for reference_count field.
	filehashDescReferenceCount := filehashFields[4].Descriptor()
	// filehash.DefaultReferenceCount holds the default value on creation for the reference_count field.
	filehash.DefaultReferenceCount = filehashDescReferenceCount.Default.(int)
	// filehashDescCreatedAt is the schema descriptor for created_at field.
	filehashDescCreatedAt := filehashFields[5].Descriptor()
	// filehash.DefaultCreatedAt holds the default value on creation for the created_at field.
	filehash.DefaultCreatedAt = filehashDescCreatedAt.Default.(func() time.Time)
	// filehashDescUpdatedAt is the schema descriptor for updated_at field.
	filehashDescUpdatedAt := filehashFields[6].Descriptor()
	// filehash.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	filehash.DefaultUpdatedAt = filehashDescUpdatedAt.Default.(func() time.Time)
	// filehash.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	filehash.UpdateDefaultUpdatedAt = filehashDescUpdatedAt.UpdateDefault.(func() time.Time)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescName is the schema descriptor for name field.
	nodeDescName := nodeFields[0].Descriptor()
	// node.NameValidator is a validator for the "name" field. It is called by the builders before save.
	node.NameValidator = nodeDescName.Validators[0].(func(string) error)
	// nodeDescType is the schema descriptor for type field.
	nodeDescType := nodeFields[1].Descriptor()
	// node.DefaultType holds the default value on creation for the type field.
	node.DefaultType = nodeDescType.Default.(int)
	// nodeDescSize is the schema descriptor for size field.
	nodeDescSize := nodeFields[2].Descriptor()
	// node.DefaultSize holds the default value on creation for the size field.
	node.DefaultSize = nodeDescSize.Default.(int64)
	// nodeDescIsDeleted is the schema descriptor for is_deleted field.
	nodeDescIsDeleted := nodeFields[6].Descriptor()
	// node.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	node.DefaultIsDeleted = nodeDescIsDeleted.Default.(bool)
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[8].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeFields[9].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() time.Time)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	shareFields := schema.Share{}.Fields()
	_ = shareFields
	// shareDescCode is the schema descriptor for code field.
	shareDescCode := shareFields[0].Descriptor()
	// share.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	share.CodeValidator = shareDescCode.Validators[0].(func(string) error)
	// shareDescShareType is the schema descriptor for share_type field.
	shareDescShareType := shareFields[1].Descriptor()
	// share.DefaultShareType holds the default value on creation for the share_type field.
	share.DefaultShareType = shareDescShareType.Default.(int)
	// shareDescAccessCount is the schema descriptor for access_count field.
	shareDescAccessCount := shareFields[4].Descriptor()
	// share.DefaultAccessCount holds the default value on creation for the access_count field.
	share.DefaultAccessCount = shareDescAccessCount.Default.(int)
	// shareDescCreatedAt is the schema descriptor for created_at field.
	shareDescCreatedAt := shareFields[6].Descriptor()
	// share.DefaultCreatedAt holds the default value on creation for the created_at field.
	share.DefaultCreatedAt = shareDescCreatedAt.Default.(func() time.Time)
	// shareDescUpdatedAt is the schema descriptor for updated_at field.
	shareDescUpdatedAt := shareFields[7].Descriptor()
	// share.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	share.DefaultUpdatedAt = shareDescUpdatedAt.Default.(func() time.Time)
	// share.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	share.UpdateDefaultUpdatedAt = shareDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescTotalQuota is the schema descriptor for total_quota field.
	userDescTotalQuota := userFields[3].Descriptor()
	// user.DefaultTotalQuota holds the default value on creation for the total_quota field.
	user.DefaultTotalQuota = userDescTotalQuota.Default.(int64)
	// userDescTotalUsed is the schema descriptor for total_used field.
	userDescTotalUsed := userFields[4].Descriptor()
	// user.DefaultTotalUsed holds the default value on creation for the total_used field.
	user.DefaultTotalUsed = userDescTotalUsed.Default.(int64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
