// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gopan-server/ent/node"
	"gopan-server/ent/share"
	"gopan-server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShareCreate is the builder for creating a Share entity.
type ShareCreate struct {
	config
	mutation *ShareMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (sc *ShareCreate) SetCode(s string) *ShareCreate {
	sc.mutation.SetCode(s)
	return sc
}

// SetShareType sets the "share_type" field.
func (sc *ShareCreate) SetShareType(i int) *ShareCreate {
	sc.mutation.SetShareType(i)
	return sc
}

// SetNillableShareType sets the "share_type" field if the given value is not nil.
func (sc *ShareCreate) SetNillableShareType(i *int) *ShareCreate {
	if i != nil {
		sc.SetShareType(*i)
	}
	return sc
}

// SetExpiresAt sets the "expires_at" field.
func (sc *ShareCreate) SetExpiresAt(t time.Time) *ShareCreate {
	sc.mutation.SetExpiresAt(t)
	return sc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (sc *ShareCreate) SetNillableExpiresAt(t *time.Time) *ShareCreate {
	if t != nil {
		sc.SetExpiresAt(*t)
	}
	return sc
}

// SetPassword sets the "password" field.
func (sc *ShareCreate) SetPassword(s string) *ShareCreate {
	sc.mutation.SetPassword(s)
	return sc
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (sc *ShareCreate) SetNillablePassword(s *string) *ShareCreate {
	if s != nil {
		sc.SetPassword(*s)
	}
	return sc
}

// SetAccessCount sets the "access_count" field.
func (sc *ShareCreate) SetAccessCount(i int) *ShareCreate {
	sc.mutation.SetAccessCount(i)
	return sc
}

// SetNillableAccessCount sets the "access_count" field if the given value is not nil.
func (sc *ShareCreate) SetNillableAccessCount(i *int) *ShareCreate {
	if i != nil {
		sc.SetAccessCount(*i)
	}
	return sc
}

// SetMaxAccessCount sets the "max_access_count" field.
func (sc *ShareCreate) SetMaxAccessCount(i int) *ShareCreate {
	sc.mutation.SetMaxAccessCount(i)
	return sc
}

// SetNillableMaxAccessCount sets the "max_access_count" field if the given value is not nil.
func (sc *ShareCreate) SetNillableMaxAccessCount(i *int) *ShareCreate {
	if i != nil {
		sc.SetMaxAccessCount(*i)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *ShareCreate) SetCreatedAt(t time.Time) *ShareCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *ShareCreate) SetNillableCreatedAt(t *time.Time) *ShareCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *ShareCreate) SetUpdatedAt(t time.Time) *ShareCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *ShareCreate) SetNillableUpdatedAt(t *time.Time) *ShareCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (sc *ShareCreate) SetOwnerID(id int) *ShareCreate {
	sc.mutation.SetOwnerID(id)
	return sc
}

// SetOwner sets the "owner" edge to the User entity.
func (sc *ShareCreate) SetOwner(u *User) *ShareCreate {
	return sc.SetOwnerID(u.ID)
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (sc *ShareCreate) SetNodeID(id int) *ShareCreate {
	sc.mutation.SetNodeID(id)
	return sc
}

// SetNode sets the "node" edge to the Node entity.
func (sc *ShareCreate) SetNode(n *Node) *ShareCreate {
	return sc.SetNodeID(n.ID)
}

// Mutation returns the ShareMutation object of the builder.
func (sc *ShareCreate) Mutation() *ShareMutation {
	return sc.mutation
}

// Save creates the Share in the database.
func (sc *ShareCreate) Save(ctx context.Context) (*Share, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ShareCreate) SaveX(ctx context.Context) *Share {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *ShareCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *ShareCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *ShareCreate) defaults() {
	if _, ok := sc.mutation.ShareType(); !ok {
		v := share.DefaultShareType
		sc.mutation.SetShareType(v)
	}
	if _, ok := sc.mutation.AccessCount(); !ok {
		v := share.DefaultAccessCount
		sc.mutation.SetAccessCount(v)
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := share.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := share.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *ShareCreate) check() error {
	if _, ok := sc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Share.code"`)}
	}
	if v, ok := sc.mutation.Code(); ok {
		if err := share.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Share.code": %w`, err)}
		}
	}
	if _, ok := sc.mutation.ShareType(); !ok {
		return &ValidationError{Name: "share_type", err: errors.New(`ent: missing required field "Share.share_type"`)}
	}
	if _, ok := sc.mutation.AccessCount(); !ok {
		return &ValidationError{Name: "access_count", err: errors.New(`ent: missing required field "Share.access_count"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Share.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Share.updated_at"`)}
	}
	if len(sc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Share.owner"`)}
	}
	if len(sc.mutation.NodeIDs()) == 0 {
		return &ValidationError{Name: "node", err: errors.New(`ent: missing required edge "Share.node"`)}
	}
	return nil
}

func (sc *ShareCreate) sqlSave(ctx context.Context) (*Share, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *ShareCreate) createSpec() (*Share, *sqlgraph.CreateSpec) {
	var (
		_node = &Share{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(share.Table, sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Code(); ok {
		_spec.SetField(share.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := sc.mutation.ShareType(); ok {
		_spec.SetField(share.FieldShareType, field.TypeInt, value)
		_node.ShareType = value
	}
	if value, ok := sc.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := sc.mutation.Password(); ok {
		_spec.SetField(share.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := sc.mutation.AccessCount(); ok {
		_spec.SetField(share.FieldAccessCount, field.TypeInt, value)
		_node.AccessCount = value
	}
	if value, ok := sc.mutation.MaxAccessCount(); ok {
		_spec.SetField(share.FieldMaxAccessCount, field.TypeInt, value)
		_node.MaxAccessCount = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(share.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_shares = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.NodeTable,
			Columns: []string{share.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.node_shares = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShareCreateBulk is the builder for creating many Share entities in bulk.
type ShareCreateBulk struct {
	config
	err      error
	builders []*ShareCreate
}

// Save creates the Share entities in the database.
func (scb *ShareCreateBulk) Save(ctx context.Context) ([]*Share, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Share, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ShareCreateBulk) SaveX(ctx context.Context) []*Share {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *ShareCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *ShareCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
