// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gopan-server/ent/node"
	"gopan-server/ent/predicate"
	"gopan-server/ent/share"
	"gopan-server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShareUpdate is the builder for updating Share entities.
type ShareUpdate struct {
	config
	hooks    []Hook
	mutation *ShareMutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (su *ShareUpdate) Where(ps ...predicate.Share) *ShareUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetCode sets the "code" field.
func (su *ShareUpdate) SetCode(s string) *ShareUpdate {
	su.mutation.SetCode(s)
	return su
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (su *ShareUpdate) SetNillableCode(s *string) *ShareUpdate {
	if s != nil {
		su.SetCode(*s)
	}
	return su
}

// SetShareType sets the "share_type" field.
func (su *ShareUpdate) SetShareType(i int) *ShareUpdate {
	su.mutation.ResetShareType()
	su.mutation.SetShareType(i)
	return su
}

// SetNillableShareType sets the "share_type" field if the given value is not nil.
func (su *ShareUpdate) SetNillableShareType(i *int) *ShareUpdate {
	if i != nil {
		su.SetShareType(*i)
	}
	return su
}

// AddShareType adds i to the "share_type" field.
func (su *ShareUpdate) AddShareType(i int) *ShareUpdate {
	su.mutation.AddShareType(i)
	return su
}

// SetExpiresAt sets the "expires_at" field.
func (su *ShareUpdate) SetExpiresAt(t time.Time) *ShareUpdate {
	su.mutation.SetExpiresAt(t)
	return su
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (su *ShareUpdate) SetNillableExpiresAt(t *time.Time) *ShareUpdate {
	if t != nil {
		su.SetExpiresAt(*t)
	}
	return su
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (su *ShareUpdate) ClearExpiresAt() *ShareUpdate {
	su.mutation.ClearExpiresAt()
	return su
}

// SetPassword sets the "password" field.
func (su *ShareUpdate) SetPassword(s string) *ShareUpdate {
	su.mutation.SetPassword(s)
	return su
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (su *ShareUpdate) SetNillablePassword(s *string) *ShareUpdate {
	if s != nil {
		su.SetPassword(*s)
	}
	return su
}

// ClearPassword clears the value of the "password" field.
func (su *ShareUpdate) ClearPassword() *ShareUpdate {
	su.mutation.ClearPassword()
	return su
}

// SetAccessCount sets the "access_count" field.
func (su *ShareUpdate) SetAccessCount(i int) *ShareUpdate {
	su.mutation.ResetAccessCount()
	su.mutation.SetAccessCount(i)
	return su
}

// SetNillableAccessCount sets the "access_count" field if the given value is not nil.
func (su *ShareUpdate) SetNillableAccessCount(i *int) *ShareUpdate {
	if i != nil {
		su.SetAccessCount(*i)
	}
	return su
}

// AddAccessCount adds i to the "access_count" field.
func (su *ShareUpdate) AddAccessCount(i int) *ShareUpdate {
	su.mutation.AddAccessCount(i)
	return su
}

// SetMaxAccessCount sets the "max_access_count" field.
func (su *ShareUpdate) SetMaxAccessCount(i int) *ShareUpdate {
	su.mutation.ResetMaxAccessCount()
	su.mutation.SetMaxAccessCount(i)
	return su
}

// SetNillableMaxAccessCount sets the "max_access_count" field if the given value is not nil.
func (su *ShareUpdate) SetNillableMaxAccessCount(i *int) *ShareUpdate {
	if i != nil {
		su.SetMaxAccessCount(*i)
	}
	return su
}

// AddMaxAccessCount adds i to the "max_access_count" field.
func (su *ShareUpdate) AddMaxAccessCount(i int) *ShareUpdate {
	su.mutation.AddMaxAccessCount(i)
	return su
}

// ClearMaxAccessCount clears the value of the "max_access_count" field.
func (su *ShareUpdate) ClearMaxAccessCount() *ShareUpdate {
	su.mutation.ClearMaxAccessCount()
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *ShareUpdate) SetCreatedAt(t time.Time) *ShareUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *ShareUpdate) SetNillableCreatedAt(t *time.Time) *ShareUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *ShareUpdate) SetUpdatedAt(t time.Time) *ShareUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (su *ShareUpdate) SetOwnerID(id int) *ShareUpdate {
	su.mutation.SetOwnerID(id)
	return su
}

// SetOwner sets the "owner" edge to the User entity.
func (su *ShareUpdate) SetOwner(u *User) *ShareUpdate {
	return su.SetOwnerID(u.ID)
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (su *ShareUpdate) SetNodeID(id int) *ShareUpdate {
	su.mutation.SetNodeID(id)
	return su
}

// SetNode sets the "node" edge to the Node entity.
func (su *ShareUpdate) SetNode(n *Node) *ShareUpdate {
	return su.SetNodeID(n.ID)
}

// Mutation returns the ShareMutation object of the builder.
func (su *ShareUpdate) Mutation() *ShareMutation {
	return su.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (su *ShareUpdate) ClearOwner() *ShareUpdate {
	su.mutation.ClearOwner()
	return su
}

// ClearNode clears the "node" edge to the Node entity.
func (su *ShareUpdate) ClearNode() *ShareUpdate {
	su.mutation.ClearNode()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ShareUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ShareUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ShareUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ShareUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *ShareUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := share.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *ShareUpdate) check() error {
	if v, ok := su.mutation.Code(); ok {
		if err := share.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Share.code": %w`, err)}
		}
	}
	if su.mutation.OwnerCleared() && len(su.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Share.owner"`)
	}
	if su.mutation.NodeCleared() && len(su.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Share.node"`)
	}
	return nil
}

func (su *ShareUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Code(); ok {
		_spec.SetField(share.FieldCode, field.TypeString, value)
	}
	if value, ok := su.mutation.ShareType(); ok {
		_spec.SetField(share.FieldShareType, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedShareType(); ok {
		_spec.AddField(share.FieldShareType, field.TypeInt, value)
	}
	if value, ok := su.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeTime, value)
	}
	if su.mutation.ExpiresAtCleared() {
		_spec.ClearField(share.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := su.mutation.Password(); ok {
		_spec.SetField(share.FieldPassword, field.TypeString, value)
	}
	if su.mutation.PasswordCleared() {
		_spec.ClearField(share.FieldPassword, field.TypeString)
	}
	if value, ok := su.mutation.AccessCount(); ok {
		_spec.SetField(share.FieldAccessCount, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedAccessCount(); ok {
		_spec.AddField(share.FieldAccessCount, field.TypeInt, value)
	}
	if value, ok := su.mutation.MaxAccessCount(); ok {
		_spec.SetField(share.FieldMaxAccessCount, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedMaxAccessCount(); ok {
		_spec.AddField(share.FieldMaxAccessCount, field.TypeInt, value)
	}
	if su.mutation.MaxAccessCountCleared() {
		_spec.ClearField(share.FieldMaxAccessCount, field.TypeInt)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(share.FieldUpdatedAt, field.TypeTime, value)
	}
	if su.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.NodeTable,
			Columns: []string{share.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.NodeTable,
			Columns: []string{share.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ShareUpdateOne is the builder for updating a single Share entity.
type ShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShareMutation
}

// SetCode sets the "code" field.
func (suo *ShareUpdateOne) SetCode(s string) *ShareUpdateOne {
	suo.mutation.SetCode(s)
	return suo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableCode(s *string) *ShareUpdateOne {
	if s != nil {
		suo.SetCode(*s)
	}
	return suo
}

// SetShareType sets the "share_type" field.
func (suo *ShareUpdateOne) SetShareType(i int) *ShareUpdateOne {
	suo.mutation.ResetShareType()
	suo.mutation.SetShareType(i)
	return suo
}

// SetNillableShareType sets the "share_type" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableShareType(i *int) *ShareUpdateOne {
	if i != nil {
		suo.SetShareType(*i)
	}
	return suo
}

// AddShareType adds i to the "share_type" field.
func (suo *ShareUpdateOne) AddShareType(i int) *ShareUpdateOne {
	suo.mutation.AddShareType(i)
	return suo
}

// SetExpiresAt sets the "expires_at" field.
func (suo *ShareUpdateOne) SetExpiresAt(t time.Time) *ShareUpdateOne {
	suo.mutation.SetExpiresAt(t)
	return suo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableExpiresAt(t *time.Time) *ShareUpdateOne {
	if t != nil {
		suo.SetExpiresAt(*t)
	}
	return suo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (suo *ShareUpdateOne) ClearExpiresAt() *ShareUpdateOne {
	suo.mutation.ClearExpiresAt()
	return suo
}

// SetPassword sets the "password" field.
func (suo *ShareUpdateOne) SetPassword(s string) *ShareUpdateOne {
	suo.mutation.SetPassword(s)
	return suo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillablePassword(s *string) *ShareUpdateOne {
	if s != nil {
		suo.SetPassword(*s)
	}
	return suo
}

// ClearPassword clears the value of the "password" field.
func (suo *ShareUpdateOne) ClearPassword() *ShareUpdateOne {
	suo.mutation.ClearPassword()
	return suo
}

// SetAccessCount sets the "access_count" field.
func (suo *ShareUpdateOne) SetAccessCount(i int) *ShareUpdateOne {
	suo.mutation.ResetAccessCount()
	suo.mutation.SetAccessCount(i)
	return suo
}

// SetNillableAccessCount sets the "access_count" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableAccessCount(i *int) *ShareUpdateOne {
	if i != nil {
		suo.SetAccessCount(*i)
	}
	return suo
}

// AddAccessCount adds i to the "access_count" field.
func (suo *ShareUpdateOne) AddAccessCount(i int) *ShareUpdateOne {
	suo.mutation.AddAccessCount(i)
	return suo
}

// SetMaxAccessCount sets the "max_access_count" field.
func (suo *ShareUpdateOne) SetMaxAccessCount(i int) *ShareUpdateOne {
	suo.mutation.ResetMaxAccessCount()
	suo.mutation.SetMaxAccessCount(i)
	return suo
}

// SetNillableMaxAccessCount sets the "max_access_count" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableMaxAccessCount(i *int) *ShareUpdateOne {
	if i != nil {
		suo.SetMaxAccessCount(*i)
	}
	return suo
}

// AddMaxAccessCount adds i to the "max_access_count" field.
func (suo *ShareUpdateOne) AddMaxAccessCount(i int) *ShareUpdateOne {
	suo.mutation.AddMaxAccessCount(i)
	return suo
}

// ClearMaxAccessCount clears the value of the "max_access_count" field.
func (suo *ShareUpdateOne) ClearMaxAccessCount() *ShareUpdateOne {
	suo.mutation.ClearMaxAccessCount()
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *ShareUpdateOne) SetCreatedAt(t time.Time) *ShareUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableCreatedAt(t *time.Time) *ShareUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *ShareUpdateOne) SetUpdatedAt(t time.Time) *ShareUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (suo *ShareUpdateOne) SetOwnerID(id int) *ShareUpdateOne {
	suo.mutation.SetOwnerID(id)
	return suo
}

// SetOwner sets the "owner" edge to the User entity.
func (suo *ShareUpdateOne) SetOwner(u *User) *ShareUpdateOne {
	return suo.SetOwnerID(u.ID)
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (suo *ShareUpdateOne) SetNodeID(id int) *ShareUpdateOne {
	suo.mutation.SetNodeID(id)
	return suo
}

// SetNode sets the "node" edge to the Node entity.
func (suo *ShareUpdateOne) SetNode(n *Node) *ShareUpdateOne {
	return suo.SetNodeID(n.ID)
}

// Mutation returns the ShareMutation object of the builder.
func (suo *ShareUpdateOne) Mutation() *ShareMutation {
	return suo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (suo *ShareUpdateOne) ClearOwner() *ShareUpdateOne {
	suo.mutation.ClearOwner()
	return suo
}

// ClearNode clears the "node" edge to the Node entity.
func (suo *ShareUpdateOne) ClearNode() *ShareUpdateOne {
	suo.mutation.ClearNode()
	return suo
}

// Where appends a list predicates to the ShareUpdate builder.
func (suo *ShareUpdateOne) Where(ps ...predicate.Share) *ShareUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ShareUpdateOne) Select(field string, fields ...string) *ShareUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Share entity.
func (suo *ShareUpdateOne) Save(ctx context.Context) (*Share, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ShareUpdateOne) SaveX(ctx context.Context) *Share {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ShareUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ShareUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *ShareUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := share.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *ShareUpdateOne) check() error {
	if v, ok := suo.mutation.Code(); ok {
		if err := share.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Share.code": %w`, err)}
		}
	}
	if suo.mutation.OwnerCleared() && len(suo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Share.owner"`)
	}
	if suo.mutation.NodeCleared() && len(suo.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Share.node"`)
	}
	return nil
}

func (suo *ShareUpdateOne) sqlSave(ctx context.Context) (_node *Share, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Share.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, share.FieldID)
		for _, f := range fields {
			if !share.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != share.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Code(); ok {
		_spec.SetField(share.FieldCode, field.TypeString, value)
	}
	if value, ok := suo.mutation.ShareType(); ok {
		_spec.SetField(share.FieldShareType, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedShareType(); ok {
		_spec.AddField(share.FieldShareType, field.TypeInt, value)
	}
	if value, ok := suo.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeTime, value)
	}
	if suo.mutation.ExpiresAtCleared() {
		_spec.ClearField(share.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := suo.mutation.Password(); ok {
		_spec.SetField(share.FieldPassword, field.TypeString, value)
	}
	if suo.mutation.PasswordCleared() {
		_spec.ClearField(share.FieldPassword, field.TypeString)
	}
	if value, ok := suo.mutation.AccessCount(); ok {
		_spec.SetField(share.FieldAccessCount, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedAccessCount(); ok {
		_spec.AddField(share.FieldAccessCount, field.TypeInt, value)
	}
	if value, ok := suo.mutation.MaxAccessCount(); ok {
		_spec.SetField(share.FieldMaxAccessCount, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedMaxAccessCount(); ok {
		_spec.AddField(share.FieldMaxAccessCount, field.TypeInt, value)
	}
	if suo.mutation.MaxAccessCountCleared() {
		_spec.ClearField(share.FieldMaxAccessCount, field.TypeInt)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(share.FieldUpdatedAt, field.TypeTime, value)
	}
	if suo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.NodeTable,
			Columns: []string{share.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.NodeTable,
			Columns: []string{share.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Share{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
