// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gopan-server/ent/node"
	"gopan-server/ent/share"
	"gopan-server/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Share is the model entity for the Share schema.
type Share struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Unique share code
	Code string `json:"code,omitempty"`
	// 0: permanent, 1: temporary
	ShareType int `json:"share_type,omitempty"`
	// Expiration time for temporary shares
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Optional password for share
	Password string `json:"password,omitempty"`
	// Number of times accessed
	AccessCount int `json:"access_count,omitempty"`
	// Maximum access count, 0 for unlimited
	MaxAccessCount int `json:"max_access_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShareQuery when eager-loading is set.
	Edges        ShareEdges `json:"edges"`
	node_shares  *int
	user_shares  *int
	selectValues sql.SelectValues
}

// ShareEdges holds the relations/edges for other nodes in the graph.
type ShareEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Node holds the value of the node edge.
	Node *Node `json:"node,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShareEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShareEdges) NodeOrErr() (*Node, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Share) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case share.FieldID, share.FieldShareType, share.FieldAccessCount, share.FieldMaxAccessCount:
			values[i] = new(sql.NullInt64)
		case share.FieldCode, share.FieldPassword:
			values[i] = new(sql.NullString)
		case share.FieldExpiresAt, share.FieldCreatedAt, share.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case share.ForeignKeys[0]: // node_shares
			values[i] = new(sql.NullInt64)
		case share.ForeignKeys[1]: // user_shares
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Share fields.
func (s *Share) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case share.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case share.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				s.Code = value.String
			}
		case share.FieldShareType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_type", values[i])
			} else if value.Valid {
				s.ShareType = int(value.Int64)
			}
		case share.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				s.ExpiresAt = value.Time
			}
		case share.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				s.Password = value.String
			}
		case share.FieldAccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field access_count", values[i])
			} else if value.Valid {
				s.AccessCount = int(value.Int64)
			}
		case share.FieldMaxAccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_access_count", values[i])
			} else if value.Valid {
				s.MaxAccessCount = int(value.Int64)
			}
		case share.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case share.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		case share.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field node_shares", value)
			} else if value.Valid {
				s.node_shares = new(int)
				*s.node_shares = int(value.Int64)
			}
		case share.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_shares", value)
			} else if value.Valid {
				s.user_shares = new(int)
				*s.user_shares = int(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Share.
// This includes values selected through modifiers, order, etc.
func (s *Share) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Share entity.
func (s *Share) QueryOwner() *UserQuery {
	return NewShareClient(s.config).QueryOwner(s)
}

// QueryNode queries the "node" edge of the Share entity.
func (s *Share) QueryNode() *NodeQuery {
	return NewShareClient(s.config).QueryNode(s)
}

// Update returns a builder for updating this Share.
// Note that you need to call Share.Unwrap() before calling this method if this Share
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Share) Update() *ShareUpdateOne {
	return NewShareClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Share entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Share) Unwrap() *Share {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Share is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Share) String() string {
	var builder strings.Builder
	builder.WriteString("Share(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("code=")
	builder.WriteString(s.Code)
	builder.WriteString(", ")
	builder.WriteString("share_type=")
	builder.WriteString(fmt.Sprintf("%v", s.ShareType))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(s.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(s.Password)
	builder.WriteString(", ")
	builder.WriteString("access_count=")
	builder.WriteString(fmt.Sprintf("%v", s.AccessCount))
	builder.WriteString(", ")
	builder.WriteString("max_access_count=")
	builder.WriteString(fmt.Sprintf("%v", s.MaxAccessCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Shares is a parsable slice of Share.
type Shares []*Share
